<?php

namespace GL\WebsiteAdminBundle\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastFourArticles()
    {
        $result = $this->createQueryBuilder('a')
                       ->where('a.publicationDate IS NOT NULL')
                       ->orderBy('a.publicationDate', 'DESC')
                       ->setMaxResults(4)
                       ->getQuery()
                       ->getResult();
        
        return $result;
    }
}
