<?php

namespace GL\WebsiteAdminBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use GL\WebsiteAdminBundle\Entity\SubCategoryArticle;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository {

    public function getLastFourArticles() {
       
        $result = $this->createQueryBuilder('a')
                ->where('a.publicationDate IS NOT NULL')
                ->orderBy('a.publicationDate', 'DESC')
                ->setMaxResults(4)
                ->getQuery()
                ->getResult();

        return $result;
    }

    public function getArticlesBySubCategory($page, $nbPerPage, SubCategoryArticle $subCategory) {
        
        $query = $this->createQueryBuilder('a')
                ->innerJoin('a.subCategory', 'sc')
                ->addSelect('sc')
                ->where('sc.id = :subCategoryId')
                ->setParameter('subCategoryId',$subCategory->getId())
                ->orderBy('a.publicationDate', 'DESC')
                ->getQuery()
        ;

        $query  ->setFirstResult(($page - 1) * $nbPerPage)
                ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }

}
