<?php

namespace GL\WebsiteAdminBundle\Repository;

/**
 * LinkCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
