<?php

namespace GL\WebsiteAdminBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFutureFiveEvent()
    {
        $now=new \DateTime(date('Y-M-d'));
        
        $result = $this->createQueryBuilder('a')
                       ->where('a.date >= :now')
                       ->setParameter('now',$now)
                       ->orderBy('a.date', 'ASC')
                       ->setMaxResults(5)
                       ->getQuery()
                       ->getResult();
        
        return $result;
    }
    
    public function getAllFutureEvent()
    {
        $now=new \DateTime(date('Y-M-d'));
        
        $result = $this->createQueryBuilder('a')
                       ->where('a.date >= :now')
                       ->setParameter('now',$now)
                       ->orderBy('a.date', 'ASC')
                       ->getQuery()
                       ->getResult();
        
        return $result;
    }
}
