<?php

namespace GL\WebsiteAdminBundle\Repository;

/**
 * SubCategoryArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
