gl_user:
    resource: "@GLUserBundle/Resources/config/routing.yml"
    prefix:   /

gl_website_admin:
    resource: "@GLWebsiteAdminBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /
