<?php

namespace CoreBundle\Repository;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupère les défi n'ayant pas reçu de réponse pour un membre donné en paramêtre
     * 
     * @param Member $memberChallenged
     * @return array
     */
    public function getUnansweredChallenge($memberChallenged)
    {
        $result = $this->createQueryBuilder('c')
                       ->where('c.memberChallenged = :memberChallenged')
                       ->setParameter('memberChallenged',$memberChallenged)
                       ->andWhere('c.challengeAccepted IS NULL')
                       ->orderBy('c.date', 'DESC')
                       ->getQuery()
                       ->getResult();
        
        return $result;
    }
}
