<?php

namespace CoreBundle\Repository;

/**
 * ChessGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChessGameRepository extends \Doctrine\ORM\EntityRepository
{
}
