<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\ChessGame;

/**
 * MoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveRepository extends \Doctrine\ORM\EntityRepository
{
   
}
