core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:WebsitePortal:index }
    
core_article:
    path: /{category}/{subCategory}/article/{slug}
    defaults: 
        _controller: CoreBundle:WebsitePortal:article
    requirements:
        slug: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
        
core_register:
    path: /website/register
    defaults: 
        _controller: CoreBundle:WebsitePortal:register
        
core_list_current_game:
    path: /chess-game/list-current-game
    defaults: 
        _controller: CoreBundle:Chess:listCurrentGame
        
core_list_finished_game:
    path: /chess-game/list-finished-game
    defaults: 
        _controller: CoreBundle:Chess:listFinishedGame
        
core_view_game:
    path: /chess-game/view-game/{id}
    defaults: 
        _controller: CoreBundle:Chess:viewGame
    requirements:
        id: \d+
        
core_challenge_game:
    path: /chess-game/challenge
    defaults: 
        _controller: CoreBundle:Chess:challenge
        
core_challenge_decision_accept:
    path: /chess-game/challenge/decision/accept/{id}
    defaults: 
        _controller: CoreBundle:Chess:acceptChallenge
    requirements:
        id: \d+

core_challenge_decision_refuse:
    path: /chess-game/challenge/decision/refuse/{id}
    defaults: 
        _controller: CoreBundle:Chess:refuseChallenge
    requirements:
        id: \d+

core_play_game:
    path: /chess-game/play-game/{id}
    defaults: 
        _controller: CoreBundle:Chess:playGame
    requirements:
        id: \d+
 
core_game_accept_draw:
    path: /chess-game/play-game/{id}/draw
    defaults: 
        _controller: CoreBundle:Chess:acceptDraw
    requirements:
        id: \d+