gl_website_admin_homepage:
    path:     /admin
    defaults: { _controller: GLWebsiteAdminBundle:Admin:index }
    
gl_website_article_list:
    path:     /admin/articles/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:Article:list
    requirements:
        action: '(edit|validate|remove)'

gl_website_article_write:
    path: /admin/articles/write
    defaults:  
        _controller: GLWebsiteAdminBundle:Article:write

gl_website_article_edit:
    
    path: /admin/articles/edit/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Article:edit
    requirements:
        id: \d+

gl_website_article_remove:
    
    path: /admin/articles/remove/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Article:remove
    requirements:
        id: \d+
        
gl_website_article_validate:
    
    path: /admin/articles/validate/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Article:validate
    requirements:
        id: \d+

gl_website_user_list:
    path:     /admin/user/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:User:list
    requirements:
        action: '(edit|validate|remove|read)'
        
gl_website_calendar_list:
    path:     /admin/calendar/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:Calendar:list
    requirements:
        action: '(edit|remove)'
        

