gl_website_admin_homepage:
    path:     /admin
    defaults: { _controller: GLWebsiteAdminBundle:Admin:index }
    
gl_website_article_list:
    path:     /admin/articles/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:Article:list
    requirements:
        action: '(edit|validate|remove)'

gl_website_article_write:
    path: /admin/articles/write
    defaults:  
        _controller: GLWebsiteAdminBundle:Article:write

gl_website_article_edit:
    
    path: /admin/articles/edit/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Article:edit
    requirements:
        id: \d+

gl_website_article_remove:
    
    path: /admin/articles/remove/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Article:remove
    requirements:
        id: \d+
        
gl_website_article_validate:
    
    path: /admin/articles/validate/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Article:validate
    requirements:
        id: \d+

gl_website_user_list:
    path:     /admin/user/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:User:list
    requirements:
        action: '(edit|validate|remove|read)'
        
gl_website_category_event_list:
    path:     /admin/category-event/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:CategoryEvent:list
    requirements:
        action: '(edit|remove)'
        
gl_website_category_event_add:
    path: /admin/category-event/add
    defaults:  
        _controller: GLWebsiteAdminBundle:CategoryEvent:add
        
gl_website_category_event_edit:
    
    path: /admin/category-event/edit/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:CategoryEvent:edit
    requirements:
        id: \d+

gl_website_category_event_remove:
    
    path: /admin/category-event/remove/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:CategoryEvent:remove
    requirements:
        id: \d+        
 
gl_website_event_list:
    path:     /admin/event/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:Event:list
    requirements:
        action: '(edit|remove)'
        
gl_website_event_add:
    path: /admin/event/add
    defaults:  
        _controller: GLWebsiteAdminBundle:Event:add
        
gl_website_event_edit:
    
    path: /admin/event/edit/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Event:edit
    requirements:
        id: \d+

gl_website_event_remove:
    
    path: /admin/event/remove/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Event:remove
    requirements:
        id: \d+      
        
gl_website_category_article_add:
    path: /admin/category-article/add
    defaults:  
        _controller: GLWebsiteAdminBundle:CategoryArticle:add
        
gl_website_category_article_edit:
    
    path: /admin/category-article/edit/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:CategoryArticle:edit
    requirements:
        id: \d+
        
gl_website_category_article_list:
    path:     /admin/category-article/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:CategoryArticle:list
    requirements:
        action: '(edit|remove)'
        
gl_website_category_article_remove:
    
    path: /admin/category-article/remove/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:CategoryArticle:remove
    requirements:
        id: \d+

gl_website_sub_category_article_add:
    path: /admin/sub-category-article/add
    defaults:  
        _controller: GLWebsiteAdminBundle:SubCategoryArticle:add
        
gl_website_sub_category_article_edit:
    
    path: /admin/sub-category-article/edit/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:SubCategoryArticle:edit
    requirements:
        id: \d+
        
gl_website_sub_category_article_list:
    path:     /admin/sub-category-article/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:SubCategoryArticle:list
    requirements:
        action: '(edit|remove)'
        
gl_website_sub_category_article_remove:
    
    path: /admin/sub-category-article/remove/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:SubCategoryArticle:remove
    requirements:
        id: \d+
        
gl_website_link_add:
    path: /admin/link/add
    defaults:  
        _controller: GLWebsiteAdminBundle:Link:add
        
gl_website_link_edit:
    
    path: /admin/link/edit/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Link:edit
    requirements:
        id: \d+
        
gl_website_link_list:
    path:     /admin/link/list/{action}
    defaults:  
        _controller: GLWebsiteAdminBundle:Link:list
    requirements:
        action: '(edit|remove)'
        
gl_website_link_remove:
    
    path: /admin/link/remove/{id}
    defaults:
        _controller: GLWebsiteAdminBundle:Link:remove
    requirements:
        id: \d+