services:
    gl_website_admin.form.summernote:
        class: GL\WebsiteAdminBundle\Form\SummernoteType
        arguments:
            - "@gl_website_admin.form.transformer.html_purifier"
        tags:
            - { name: form.type, alias: summernote }
          
    gl_website_admin.form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: 
            - "@exercise_html_purifier.custom"
            
            
    gl_website_admin.doctrine_listener.link_listener:
        class: GL\WebsiteAdminBundle\DoctrineListener\LinkListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            
    gl_website_admin.service.link_service:
        class: GL\WebsiteAdminBundle\Services\LinkService
        arguments:
            - "@doctrine.orm.entity_manager"
            
    gl_website_admin.email.registration_mailer:
        class: GL\WebsiteAdminBundle\Email\RegistrationMailer
        arguments:
            - "@mailer"
            - [%mailer_user%]
   